package com.example.tpi_mobile_001.ui.components

fun getBandera(equipo: String): String {
    return when (equipo) {
        "México" -> "🇲🇽"
        "Sudáfrica" -> "🇿🇦"
        "Corea del Sur" -> "🇰🇷"
        "Chequia" -> "🇨🇿"
        "Canadá" -> "🇨🇦"
        "Bosnia y Herzegovina" -> "🇧🇦"
        "Estados Unidos" -> "🇺🇸"
        "Paraguay" -> "🇵🇾"
        "Catar" -> "🇶🇦"
        "Suiza" -> "🇨🇭"
        "Brasil" -> "🇧🇷"
        "Marruecos" -> "🇲🇦"
        "Haití" -> "🇭🇹"
        "Escocia" -> "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
        "Australia" -> "🇦🇺"
        "Turquía" -> "🇹🇷"
        "Alemania" -> "🇩🇪"
        "Curazao" -> "🇨🇼"
        "Países Bajos" -> "🇳🇱"
        "Japón" -> "🇯🇵"
        "Costa de Marfil" -> "🇨🇮"
        "Ecuador" -> "🇪🇨"
        "Suecia" -> "🇸🇪"
        "Túnez" -> "🇹🇳"
        "España" -> "🇪🇸"
        "Arabia Saudita" -> "🇸🇦"
        "Uruguay" -> "🇺🇾"
        "Cabo Verde" -> "🇨🇻"
        "Francia" -> "🇫🇷"
        "Nigeria" -> "🇳🇬"
        "Senegal" -> "🇸🇳"
        "Nueva Zelanda" -> "🇳🇿"
        "Croacia" -> "🇭🇷"
        "Irán" -> "🇮🇷"
        "Irak" -> "🇮🇶"
        "Noruega" -> "🇳🇴"
        "Argentina" -> "🇦🇷"
        "Austria" -> "🇦🇹"
        "Argelia" -> "🇩🇿"
        "Jordania" -> "🇯🇴"
        "Inglaterra" -> "🏴󠁧󠁢󠁥󠁮󠁧󠁿"
        "Ghana" -> "🇬🇭"
        "Panamá" -> "🇵🇦"
        "Portugal" -> "🇵🇹"
        "RD Congo" -> "🇨🇩"
        "Uzbekistán" -> "🇺🇿"
        "Colombia" -> "🇨🇴"
        else -> "🏳️"
    }
}